#ifndef _ENGINE_CONF_H
#define _ENGINE_CONF_H

#define MAX_TEXTURES 16
#define MAX_SPRITES 64
#define MAX_SOUNDS 32
#define MAX_FONTS 4
#define MAX_N_TILES 4096
#define MAX_NAME_LEN 32
#define MAX_LEVEL_PACK 4
#define N_SFX 32
#define MAX_EMITTER_CONF 8
//#define MAX_PARTICLE_EMITTER 8
#define MAX_ACTIVE_PARTICLE_EMITTER 128
#define MAX_PARTICLES 32

#define MAX_TILE_TYPES 16

#define N_TAGS 10
#define N_COMPONENTS 15
#define MAX_COMP_POOL_SIZE 4096
#endif // _ENGINE_CONF_H
